### ISSUE TITLE
The plugin name

### ISSUE THREAD

**Issue by hlaueriksson** [Fefedu973/PowerToys-Run-Google-Search-Suggestions-Plugin#1]
Hi @Fefedu973

The name of the plugin suggests that Google is the only search engine that is supported.

I count to 22 [searchEngines](https://github.com/Fefedu973/PowerToys-Run-Google-Search-Suggestions-Plugin/blob/01fdf3a99da29f98c46454689c6e34e054f65f7f/src/Main.cs#L28).

It would be nice if the name gives this broader picture.

**Comment by Fefedu973** [comment]
Yes I see, I'm going to change that, in the beginning only google was supported this is why.
By the way there are 22 search engines where I can be redirected to but "only" 8 from which I can grab the suggestions

**Comment by Fefedu973** [comment]
I've changed the name in github, I'm currently working on an update that will fix some bugs, add a plugin updater app, allows you to always search with the plugin (even if there is no results from suggestions) and I will change the plugin name in the mean time as well as the logo

**Comment by Fefedu973** [comment]
Update Done ! ✅
